name: Deploy to FichaRPG

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x.x'
    
    - name: Restore dependencies
      run: dotnet restore ./FichaRPG/FichaRPG.sln
    
    - name: Build
      run: dotnet build ./FichaRPG/FichaRPG.sln -c Release --no-restore
    
    - name: Publish
      run: dotnet publish ./FichaRPG/FichaRPG.sln -c Release --no-build -o ./publish

    - name: Create tarball
      run: tar --no-same-permissions -cvf publish.tar ./publish
    
    - name: Deploy to FichaRPG
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWORD }}
        source: './publish'
        target: '/var/www/html/FichaRPG'
        port: 22
    
    - name: Restart service
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.VM_HOST}}
        username: ${{secrets.VM_USERNAME}}
        password: ${{secrets.VM_PASSWORD}}
        script: |
          echo "${{ secrets.VM_PASSWORD }}" | sudo -S systemctl restart FichaRPG.service
      env:
        VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
