name: Deploy to FichaRPG

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x.x'
    
    - name: Restore dependencies
      run: dotnet restore ./FichaRPG/FichaRPG.sln
    
    - name: Build
      run: dotnet build ./FichaRPG/FichaRPG.sln -c Release --no-restore
    
    - name: Publish
      run: dotnet publish ./FichaRPG/FichaRPG.sln -c Release --no-build -o ./publish
    
    - name: Deploy to FichaRPG
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
          username: 'capitao-tchaka'
          server: ${{secrets.VM_HOST}}
          ssh_private_key: ${{secrets.VM_PASSWORD }} 
          local_path: './publish'
          remote_path: '/home/capitao-tchaka/Release/net6.0/publish'
    
    - name: Restart service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWORD }}
        script: |
          sudo systemctl restart ficha-rpg.service
          
